# Optional - The name of the workflow as it will appear in the "Actions" tab of the GitHub repository. If this field is omitted, the name of the workflow file will be used instead.
name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:

  check-bats-version:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6
      - name: Set up Python

      - uses: actions/setup-node@v4
      - name: Install dependencies

        run: pip install -r requirements.txt # Або інша команда, яку ви використовуєте
      - name: Run tests
      
        run: python test_main.py